### ISSUE TITLE
Combination of ESXi and BareMetal

### ISSUE THREAD

**Issue by RajathAV** [ryanhay/ocp4-metal-install#1]
This is more of a question rather than an issue @ryanhay . I would like to know if i can use a combination of ESXi and bare metals? I can spin up all the control plane on bare metal and even worker nodes on bare metals and keep services and bootstrap on the ESXi server? 

My catch here is that the OCP network(2nd network that we create) how do i bridge that to my VMs? Also my bootstrap machine which is on ESXi is on the OCP network. But unable to fetch files from the Centos VM. Im a newbie to this, so these might sound like basic questions. Any help would be appreciated.

**Comment by ryanhay** [comment]
Hi @RajathAV it is definitely possible to do what you would like to do, its just a matter of getting the networking right. Unfortunately thats difficult for me to comment exactly how you would do that as its dependant on your environment. If you are new and would like to keep things simple for your testing environment you can always just use a flat network and spin everything up using your routers default network so that everything in your environment is routable pretty much for free. Otherwise you will need to create network gateways and probably manually setup some CoreOS static routes (https://coreos.com/os/docs/latest/network-config-with-networkd.html) or use DHCP to distribute them.

**Comment by AvRajath** [comment]
Thanks will have a look into it
